code: import PYTHON_VERSION
fixup on commit 7fddc7fde65174396dac9657e808341b520f13ed

without this change, calling freeze on a code object
would error out with

    NameError: name 'PYTHON_VERSION' is not defined