When a .pyc file cannot be opened, this is the error message:
    Traceback (most recent call last):
      File "/home/jeff/.local/bin/uncompyle6", line 11, in <module>
        sys.exit(main_bin())
      File "/home/jeff/.local/lib/python2.7/site-packages/uncompyle6/bin/uncompile.py", line 181, in main_bin
        **options)
      File "/home/jeff/.local/lib/python2.7/site-packages/uncompyle6/main.py", line 223, in main
        linemap_stream, do_fragments)
      File "/home/jeff/.local/lib/python2.7/site-packages/uncompyle6/main.py", line 126, in decompile_file
        source_size) = load_module(filename, code_objects)
      File "/home/jeff/.local/lib/python2.7/site-packages/xdis/load.py", line 110, in load_module
        fp.close()
    UnboundLocalError: local variable 'fp' referenced before assignment

Changed to use with context handler so that the real exception is raised:

    Traceback (most recent call last):
      File "/home/jeff/.local/bin/uncompyle6", line 11, in <module>
        sys.exit(main_bin())
      File "/home/jeff/.local/lib/python2.7/site-packages/uncompyle6/bin/uncompile.py", line 181, in main_bin
        **options)
      File "/home/jeff/.local/lib/python2.7/site-packages/uncompyle6/main.py", line 223, in main
        linemap_stream, do_fragments)
      File "/home/jeff/.local/lib/python2.7/site-packages/uncompyle6/main.py", line 126, in decompile_file
        source_size) = load_module(filename, code_objects)
      File "build/bdist.linux-x86_64/egg/xdis/load.py", line 105, in load_module
    IOError: [Errno 13] Permission denied: 'test.pyc'